name: Quarkiverse Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{github.event.pull_request.merged == true}}

    steps:
      - uses: radcortez/project-metadata-action@master
        name: Retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - uses: actions/checkout@v3

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Maven release ${{steps.metadata.outputs.current-version}}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.GPG_PASSPHRASE}}" --output maven-settings.xml .github/release/maven-settings.xml.gpg
          git checkout -b release
          mvn -B release:prepare -DpreparationGoals="clean install" -DskipTests -Darguments=-DskipTests -Prelease -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}} -s maven-settings.xml
          git commit -am "Update stable version for documentation"
          git checkout ${{github.base_ref}}
          git rebase release
          mvn -B release:perform -DskipTests -Darguments="-DperformRelease -DskipTests" -Prelease -s maven-settings.xml

      - name: Adjust tag for documentation changes
        run: |
          git checkout ${{steps.metadata.outputs.current-version}}
          mvn -B clean install -DskipTests -DskipITs
          git commit -am "Update stable version for documentation"
          # Move the tag after inclusion of documentation adjustments
          git tag -f ${{steps.metadata.outputs.current-version}}
          # Go back to base branch
          git checkout ${{github.base_ref}}

      - name: Push changes to ${{github.base_ref}}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.base_ref}}

      - name: Push tags
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.base_ref}}
          tags: true
